/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lessons' | '/tutor' | '/api/chat' | '/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lessons' | '/tutor' | '/api/chat' | '/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsRoute: typeof LessonsRoute
  TutorRoute: typeof TutorRoute
  ApiChatRoute: typeof ApiChatRoute
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsRoute: LessonsRoute,
  TutorRoute: TutorRoute,
  ApiChatRoute: ApiChatRoute,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
