/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSectionIdRouteImport } from './routes/section.$sectionId'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionIdRoute = SectionSectionIdRouteImport.update({
  id: '/section/$sectionId',
  path: '/section/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tts': typeof ApiTtsRoute
  '/section/$sectionId': typeof SectionSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/api/tts'
    | '/section/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/api/tts'
    | '/section/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/api/tts'
    | '/section/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonsRoute: typeof LessonsRoute
  TutorRoute: typeof TutorRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTtsRoute: typeof ApiTtsRoute
  SectionSectionIdRoute: typeof SectionSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$sectionId': {
      id: '/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/section/$sectionId'
      preLoaderRoute: typeof SectionSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonsRoute: LessonsRoute,
  TutorRoute: TutorRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTtsRoute: ApiTtsRoute,
  SectionSectionIdRoute: SectionSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
