/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorRouteImport } from './routes/tutor'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSectionIdRouteImport } from './routes/section.$sectionId'
import { Route as PracticeUnitRouteImport } from './routes/practice.$unit'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiExercisesRouteImport } from './routes/api/exercises'
import { Route as ApiExamRouteImport } from './routes/api/exam'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as PracticeUnitSkillRouteImport } from './routes/practice.$unit.$skill'

const TutorRoute = TutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSectionIdRoute = SectionSectionIdRouteImport.update({
  id: '/section/$sectionId',
  path: '/section/$sectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeUnitRoute = PracticeUnitRouteImport.update({
  id: '/practice/$unit',
  path: '/practice/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExercisesRoute = ApiExercisesRouteImport.update({
  id: '/api/exercises',
  path: '/api/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamRoute = ApiExamRouteImport.update({
  id: '/api/exam',
  path: '/api/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeUnitSkillRoute = PracticeUnitSkillRouteImport.update({
  id: '/$skill',
  path: '/$skill',
  getParentRoute: () => PracticeUnitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exam': typeof ApiExamRoute
  '/api/exercises': typeof ApiExercisesRoute
  '/api/tts': typeof ApiTtsRoute
  '/practice/$unit': typeof PracticeUnitRouteWithChildren
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/practice/$unit/$skill': typeof PracticeUnitSkillRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exam': typeof ApiExamRoute
  '/api/exercises': typeof ApiExercisesRoute
  '/api/tts': typeof ApiTtsRoute
  '/practice/$unit': typeof PracticeUnitRouteWithChildren
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/practice/$unit/$skill': typeof PracticeUnitSkillRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lessons': typeof LessonsRoute
  '/tutor': typeof TutorRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exam': typeof ApiExamRoute
  '/api/exercises': typeof ApiExercisesRoute
  '/api/tts': typeof ApiTtsRoute
  '/practice/$unit': typeof PracticeUnitRouteWithChildren
  '/section/$sectionId': typeof SectionSectionIdRoute
  '/practice/$unit/$skill': typeof PracticeUnitSkillRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/api/exam'
    | '/api/exercises'
    | '/api/tts'
    | '/practice/$unit'
    | '/section/$sectionId'
    | '/practice/$unit/$skill'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/api/exam'
    | '/api/exercises'
    | '/api/tts'
    | '/practice/$unit'
    | '/section/$sectionId'
    | '/practice/$unit/$skill'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/lessons'
    | '/tutor'
    | '/api/chat'
    | '/api/exam'
    | '/api/exercises'
    | '/api/tts'
    | '/practice/$unit'
    | '/section/$sectionId'
    | '/practice/$unit/$skill'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LessonsRoute: typeof LessonsRoute
  TutorRoute: typeof TutorRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExamRoute: typeof ApiExamRoute
  ApiExercisesRoute: typeof ApiExercisesRoute
  ApiTtsRoute: typeof ApiTtsRoute
  PracticeUnitRoute: typeof PracticeUnitRouteWithChildren
  SectionSectionIdRoute: typeof SectionSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutor': {
      id: '/tutor'
      path: '/tutor'
      fullPath: '/tutor'
      preLoaderRoute: typeof TutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$sectionId': {
      id: '/section/$sectionId'
      path: '/section/$sectionId'
      fullPath: '/section/$sectionId'
      preLoaderRoute: typeof SectionSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$unit': {
      id: '/practice/$unit'
      path: '/practice/$unit'
      fullPath: '/practice/$unit'
      preLoaderRoute: typeof PracticeUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exercises': {
      id: '/api/exercises'
      path: '/api/exercises'
      fullPath: '/api/exercises'
      preLoaderRoute: typeof ApiExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam': {
      id: '/api/exam'
      path: '/api/exam'
      fullPath: '/api/exam'
      preLoaderRoute: typeof ApiExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$unit/$skill': {
      id: '/practice/$unit/$skill'
      path: '/$skill'
      fullPath: '/practice/$unit/$skill'
      preLoaderRoute: typeof PracticeUnitSkillRouteImport
      parentRoute: typeof PracticeUnitRoute
    }
  }
}

interface PracticeUnitRouteChildren {
  PracticeUnitSkillRoute: typeof PracticeUnitSkillRoute
}

const PracticeUnitRouteChildren: PracticeUnitRouteChildren = {
  PracticeUnitSkillRoute: PracticeUnitSkillRoute,
}

const PracticeUnitRouteWithChildren = PracticeUnitRoute._addFileChildren(
  PracticeUnitRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LessonsRoute: LessonsRoute,
  TutorRoute: TutorRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExamRoute: ApiExamRoute,
  ApiExercisesRoute: ApiExercisesRoute,
  ApiTtsRoute: ApiTtsRoute,
  PracticeUnitRoute: PracticeUnitRouteWithChildren,
  SectionSectionIdRoute: SectionSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
